server:
  port: 8089
  servlet:
    context-path: /
  max-http-request-header-size: 30KB

# 配置数据库的连接信息（配置数据源）
spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

  #配置redis的连接信息
  data:
    redis:
      host: 111.119.211.126
      port: 6379
      password: 1234
      database: 0

  #让spring支持bean的循环依赖, BeanA 依赖 BeanB，同时BeanB也依赖BeanA，这就是循环依赖
  main:
    allow-circular-references: true

  #后端对象返回json时，指定日期时区和日期格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#指定mapper.xml文件在什么位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #配置mybatis框架执行sql语句时，把sql语句打印到控制台
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#项目启动日志的打印级别
logging:
  level:
    com:
      zw:
        mapper: debug
        service: info
        web: info


